name: my_app
description: "DropGlass hydration reminder"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/glass_empty.png
